### ISSUE TITLE
help please!!!

### ISSUE THREAD

**Issue by hmm-star** [Pud-of-Mud/Quizlet-Account-Generator#1]
i am getting this error :
```
 C:\Users\v\Downloads\Quizlet-Account-Generator-main>python main.py
Traceback (most recent call last):
  File "C:\Users\v\Downloads\Quizlet-Account-Generator-main\main.py", line 4, in <module>
    erl = webbot.Browser()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\v\AppData\Local\Programs\Python\Python312\Lib\site-packages\webbot\webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
```

**Comment by Pud-of-Mud** [comment]
@hmm-star,

This code is showing its age as it was initially programmed a while ago and the signup process might've changed since. I started contemplating a complete rewrite, so that might come in a few weeks; but I digress.

This error occurred because 'webbot' cannot find your browser install. By default, it uses Chrome for automation; it has yet to find your directory for such automation.  This can be from either not having Chrome installed or failing to redirect webbot to its location. 

If you don't have chrome installed, ensure you do that as a possible solution. If you already have it installed, I committed a change to the repository that may rid you of that error.

Cheers,
@Pud-of-Mud

**Comment by hmm-star** [comment]
Greetings
I am so thankful for your quick response. I would like to mention that as per your instructions, i also replaced the `webbot.py` with the one you mentioned here. Moreover, i also have chrome installed already. i am still getting the error below:
```
Traceback (most recent call last):
  File "C:\Users\v\Downloads\Quizlet-Account-Generator-main\main.py", line 1, in <module>
    import webbot
  File "C:\Users\v\AppData\Local\Programs\Python\Python312\Lib\site-packages\webbot\__init__.py", line 1, in <module>
    from .webbot import Browser
  File "C:\Users\v\AppData\Local\Programs\Python\Python312\Lib\site-packages\webbot\webbot.py", line 8, in <module>
    import undetected_chromedriver as uc
ModuleNotFoundError: No module named 'undetected_chromedriver'

``
Regards
@hmm-star

**Comment by Pud-of-Mud** [comment]
Try and install (or reinstall) the ```undetected_chromedriver``` module that it states is missing.  Run the following command in a terminal of your choice:
```
pip install undetected-chromedriver
pip show undetected-chromedriver
```
Then, try to re-run the program and ensure that you are using the most recent push from the repository. I made some changes to try to help your situation; however, those changes have not been tested yet, so you may run into some other issues with the new code.

Cheers,
@Pud-of-Mud

**Comment by hmm-star** [comment]
Thank you so much for you quick help. I have followed everything including your latest instructions. I gave some other comands and reached the following But still i am getting an error :
```
Do you want a single account or many accounts under one email address?
Traceback (most recent call last):
  File "C:\Users\v\Downloads\Quizlet-Account-Generator-main\main.py", line 13, in <module>
    while repeat != "single" or "multi":
          ^^^^^^
NameError: name 'repeat' is not defined
Exception ignored in: <function Chrome.__del__ at 0x000002B3DBEB8540>
Traceback (most recent call last):
  File "C:\Users\v\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\v\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] The handle is invalid
```
please take a look at this 
Best Regards
@hmm-star

**Comment by hmm-star** [comment]
any fix sir ?
